### ISSUE TITLE
Support username and password with curl for reusable workflow

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/preview-action#4]
Uffizzi Cloud platform now allows users to set up a username and password for preview URLs; however, this breaks the current reusable workflow because the `curl` command that confirms successful deployment cannot access the URL.

We should add support for passing username and password to the curl command [here](https://github.com/UffizziCloud/preview-action/blob/6504e1578015e5470858bfe7e7793779fa01b6a4/.github/workflows/reusable.yaml#L115-L117) and [here](https://github.com/UffizziCloud/preview-action/blob/6504e1578015e5470858bfe7e7793779fa01b6a4/.github/workflows/reusable.yaml#L148-L150).  

Inputs should be non-interactive. Username can probably be passed via flag (`-u`), but password should probably be passed via environment variable (e.g. `URL_PASSWORD`).

**Comment by gadkins** [comment]
This means that the reusable workflow should support optional `preview-username` and `preview-password` parameters. So, when using the reusable workflow in a job, the user can specify something like:  

```
  deploy-uffizzi-preview:
    name: Use Remote Workflow to Preview on Uffizzi
    needs: render-compose-file
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@reusable-workflow
    if: github.event_name == 'pull_request'
    with:
      compose-file-cache-key: ${{ needs.render-compose-file.outputs.compose-file-cache-key }}
      compose-file-cache-path: docker-compose.rendered.yml
      username: josh@idyl.tech
      server: https://app.uffizzi.com
      project: vote-app-latest-m57p
      preview-username: admin
      preview-password: : ${{ secrets.PREVIEW_PASSWORD }}
    secrets:
      password: ${{ secrets.UFFIZZI_PASSWORD }}
    permissions:
      contents: read
      pull-requests: write
```

**Comment by gadkins** [comment]
After implementing this, let's add these lines (commented out) to our example-voting-app workflow:

``` yaml
    [...]
    with:
      compose-file-cache-key: ${{ needs.render-compose-file.outputs.compose-file-cache-key }}
      compose-file-cache-path: docker-compose.rendered.yml
      username: josh@idyl.tech
      server: https://app.uffizzi.com
      project: vote-app-latest-m57p
      # preview-username: admin    # for password-protected preview URLs
      # preview-password: : ${{ secrets.PREVIEW_PASSWORD }}    # for password-protected preview URLs
```
